### ISSUE TITLE
Issue with Libc-GOT-Hijacking Method on Newer Libc Versions (2.37, 2.38)

### ISSUE THREAD

**Issue by AvavaAYA** [n132/Libc-GOT-Hijacking#1]
Hello,

I have been experimenting with the Libc-GOT-Hijacking attack method outlined in this repository. During my tests, I observed that while the method works as expected on libc version 2.35, it seems to fail on the newer libc versions 2.37 and 2.38.

Specifically, in versions 2.37 and above, I noticed that the GOT (Global Offset Table) header in libc is no longer writable, which effectively prevents the injection of the payload. This behavior was consistently observed during debugging in both 2.37 and 2.38 versions.

This leads me to wonder whether the current approach of the Libc-GOT-Hijacking method has become ineffective or outdated due to recent security enhancements in libc. 

- glibc version: GLIBC 2.37-0ubuntu2.1
- OS: Ubuntu 23.10

Screenshot:
![gdb](https://github.com/n132/Libc-GOT-Hijacking/assets/97781235/53b646a4-f219-4bca-b4e7-de1c2588a9fe)

**Comment by n132** [comment]
Hi @AvavaAYA, 

I verified your issue. It's true. This method can't work for these libraries since we can overwrite the metadata just before GOTtables. We should think about a new way to construct stable RCE. More work is needed. I don't have much time in the next month. But I'll work on this after I finish the next month.

Also, here are some ideas that may deliver a stable exploitation:
X gadgets:
1) We can still overwrite the GOT area, it's not likely to use x_gadget to get a shell since there are some constraints
2) Combining X gadgets
For example,
As we know `printf` hits slot 6 and `asctime` hits slot 1. 
We can make
slot[6] = asctime+0x? (nudge the stack)
slot[1] = one_gadget
So the following gadget could work. 
```
0x11060a posix_spawn(rsp+0x64, "/bin/sh", [rsp+0x48], 0, rsp+0x70, [rsp+0xf0])
constraints:
  [rsp+0x70] == NULL
  [[rsp+0xf0]] == NULL || [rsp+0xf0] == NULL
  [rsp+0x48] == NULL || (s32)[[rsp+0x48]+0x4] <= 0
```
I need more time to work on this and make everything automatic. I'll keep this issue til I solve the issue and add one note to the readme file to make sure people notice this fact. 

Thanks for the reminder,
n132

**Comment by n132** [comment]
Hi @AvavaAYA,

Uptade for my idea: I proved that we use it to exploit. But I have no time now to finish it. Asked my friends for help, they may make a pr and make this method more useful. 

The following figure is for glibc-2.38. This method needs to be generalized (which my friend is doing). 

![X](https://github.com/n132/Libc-GOT-Hijacking/assets/27342439/d2d86321-b793-4cd5-9124-5118a7fff3f7)

Thanks,
n132

**Comment by n132** [comment]
@AvavaAYA 
This commit provides a way to exploit. I'll close this issue and later update the tool for that method with my friends. 

https://github.com/n132/Libc-GOT-Hijacking/commit/19206fa54d374371ea642c1979dbca216b95dbbe
